### ISSUE TITLE
Date parsing issue in WSL

### ISSUE THREAD

**Issue by ihabunek** [ihabunek/toot#111]
```
Traceback (most recent call last):
  File "/home/ihabunek/projects/toot/toot/tui/app.py", line 153, in _done
    result = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ihabunek/projects/toot/toot/tui/app.py", line 246, in _load_statuses
    return [Status(s, self.app.instance) for s in data]
  File "/home/ihabunek/projects/toot/toot/tui/app.py", line 246, in <listcomp>
    return [Status(s, self.app.instance) for s in data]
  File "/home/ihabunek/projects/toot/toot/tui/entities.py", line 35, in __init__
    self.created_at = parse_datetime(data["created_at"])
  File "/home/ihabunek/projects/toot/toot/tui/utils.py", line 12, in parse_datetime
    return datetime.strptime(value, "%Y-%m-%dT%H:%M:%S.%f%z").astimezone()
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2019-09-01T07:26:05.000Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
(toot) ihabunek@tomodachi:~/projects/toot$
```

**Comment by ihabunek** [comment]
Duplicate of #114
