### ISSUE TITLE
`toot tui` crashes by KeyError: 'author_name' with pleroma instance

### ISSUE THREAD

**Issue by ynakao** [ihabunek/toot#116]
Thank you for the great software.

It might not be a toot's issue because I use it with [Pleroma](https://pleroma.social/), which is a Mastodon compatible federated SNS server. When I tried to open curses view by newly introduced `$ toot tui` command, toot crashed claiming `KeyError: 'author_name'` after typing `j` to see the next post. Please refer to full traceback below. `$ toot curses` and `$ toot timeline` still work fine.

I'm on Arch Linux and toot v0.23.1.

```
Traceback (most recent call last):
  File "/usr/bin/toot", line 11, in <module>
    load_entry_point('toot==0.23.1', 'console_scripts', 'toot')()
  File "/usr/lib/python3.7/site-packages/toot/console.py", line 545, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3.7/site-packages/toot/console.py", line 527, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3.7/site-packages/toot/commands.py", line 331, in tui
    TUI.create(app, user).run()
  File "/usr/lib/python3.7/site-packages/toot/tui/app.py", line 108, in run
    self.loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.7/site-packages/toot/tui/timeline.py", line 147, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3.7/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.7/site-packages/urwid/listbox.py", line 1013, in keypress
    return actual_key(self._keypress_down((maxcol, maxrow)))
  File "/usr/lib/python3.7/site-packages/urwid/listbox.py", line 1136, in _keypress_down
    row_offset, 'above')
  File "/usr/lib/python3.7/site-packages/urwid/listbox.py", line 857, in change_focus
    self._body.set_focus(position)
  File "/usr/lib/python3.7/site-packages/urwid/listbox.py", line 239, in set_focus
    self._modified()
  File "/usr/lib/python3.7/site-packages/urwid/listbox.py", line 43, in _modified
    signals.emit_signal(self, "modified")
  File "/usr/lib/python3.7/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.7/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.7/site-packages/toot/tui/timeline.py", line 81, in modified
    self.draw_status_details(status)
  File "/usr/lib/python3.7/site-packages/toot/tui/timeline.py", line 90, in draw_status_details
    self.status_details = StatusDetails(status, self.is_thread)
  File "/usr/lib/python3.7/site-packages/toot/tui/timeline.py", line 191, in __init__
    widget_list = list(self.content_generator(status))
  File "/usr/lib/python3.7/site-packages/toot/tui/timeline.py", line 234, in content_generator
    yield ("pack", self.build_linebox(self.card_generator(card)))
  File "/usr/lib/python3.7/site-packages/toot/tui/timeline.py", line 256, in build_linebox
    contents = urwid.Pile(list(contents))
  File "/usr/lib/python3.7/site-packages/toot/tui/timeline.py", line 262, in card_generator
    if card["author_name"]:
KeyError: 'author_name'
```

**Comment by hushroom** [comment]
I see this bug too, unfamiliar with this application and AP in general, but fixed the immediate KeyError by changing this instance of `dict["key"]` to `dict.get("key") ` which returns None if key doesn't exist in myDict rather than KeyError. 

I checked for other instances of this code pattern too and there are more cases like this that would cause a similar crash if an implementation returns a dict missing a key, rather than `dict["key"]=None`
I'm not sure if they should be fixed in the same manner? or if some of these would be a sign of malformed content that SHOULD cause a crash?

~/dev/toot/toot$ rg "if [a-zA-Z]+\[" .
./commands.py
246:        if account['acct'] == account_name:

./tui/timeline.py
239:                if m["description"]:
292:        if card["description"]:
300:                if poll["votes_count"] else 0)
304:        if poll["expired"]:

./config.py
92:    if config['active_user']:
166:    if config['active_user'] == user_id(user):

./ui/parsers.py
11:    boosted_by = parse_account(status['account']) if status['reblog'] else None

./ui/app.py
136:        if status['account']['display_name']:
141:        if status['in_reply_to_id'] is not None:
148:        if status['favourited']:
204:        if status['sensitive']:
209:        if status['sensitive'] and not status['show_sensitive']:
216:        if status['media_attachments']:
223:        if status['url'] is not None:
226:        if status['boosted_by']:
230:        if status['reblogged']:
619:        if status['sensitive'] and not status['show_sensitive']:
681:        if status['reblogged']:
703:        if status['favourited']:

**Comment by ynakao** [comment]
After v0.24.0 released, this issue seemed to be resolved. Thanks.
