### ISSUE TITLE
'toot tui' crashes with "Unrecognised color specification"

### ISSUE THREAD

**Issue by highvoltage** [ihabunek/toot#124]
I build a debian package from the 0.23.1 sources and when running 'toot tui', I get the following:

```
$ toot tui
Traceback (most recent call last):
  File "/usr/bin/toot", line 11, in <module>
    load_entry_point('toot==0.23.1', 'console_scripts', 'toot')()
  File "/usr/lib/python3/dist-packages/toot/console.py", line 545, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 527, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 331, in tui
    TUI.create(app, user).run()
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 79, in create
    unhandled_input=tui.unhandled_input,
  File "/home/jonathan/.local/lib/python3.7/site-packages/urwid/main_loop.py", line 114, in __init__
    screen.register_palette(palette)
  File "/home/jonathan/.local/lib/python3.7/site-packages/urwid/display_common.py", line 778, in register_palette
    self.register_palette_entry(*item)
  File "/home/jonathan/.local/lib/python3.7/site-packages/urwid/display_common.py", line 845, in register_palette_entry
    basic = AttrSpec(foreground, background, 16)
  File "/home/jonathan/.local/lib/python3.7/site-packages/urwid/display_common.py", line 489, in __init__
    self.foreground = fg
  File "/home/jonathan/.local/lib/python3.7/site-packages/urwid/display_common.py", line 578, in _set_foreground
    "in foreground (%s)") % (repr(part), repr(foreground)))
urwid.display_common.AttrSpecError: Unrecognised color specification 'italics'in foreground (',italics')
```

**Comment by ihabunek** [comment]
I cannot reproduce this on a clean Debian 10 machine. What version of Urwid do you have installed? I think you may have urwid 1.x, and toot requires urwid 2.x.

**Comment by highvoltage** [comment]
Debian has urwid 2.x, will check again tonight, maybe I had something old installed via pip.

**Comment by ihabunek** [comment]
@highvoltage I'm guessing this can be closed since 0.23.1 was accepted into testing?

**Comment by highvoltage** [comment]
I'm not sure what went wrong before but it seems to work fine for me now, so yes, closing...

**Comment by tshrinivasan** [comment]
I get the same issue with toot v.0.24.0 in ubuntu 18.04 today

shrinivasan@shrinivasan-Lenovo-Z50-70:~$ toot tui
Traceback (most recent call last):
  File "/usr/local/bin/toot", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/toot/console.py", line 545, in main
    run_command(app, user, command_name, args)
  File "/usr/local/lib/python3.6/dist-packages/toot/console.py", line 527, in run_command
    return fn(app, user, parsed_args)
  File "/usr/local/lib/python3.6/dist-packages/toot/commands.py", line 331, in tui
    TUI.create(app, user).run()
  File "/usr/local/lib/python3.6/dist-packages/toot/tui/app.py", line 82, in create
    unhandled_input=tui.unhandled_input,
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 114, in __init__
    screen.register_palette(palette)
  File "/usr/local/lib/python3.6/dist-packages/urwid/display_common.py", line 785, in register_palette
    self.register_palette_entry(*item)
  File "/usr/local/lib/python3.6/dist-packages/urwid/display_common.py", line 852, in register_palette_entry
    basic = AttrSpec(foreground, background, 16)                                                                                                                                             
  File "/usr/local/lib/python3.6/dist-packages/urwid/display_common.py", line 489, in __init__                                                                                               
    self.foreground = fg                                                                                                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/urwid/display_common.py", line 578, in _set_foreground
    "in foreground (%s)") % (repr(part), repr(foreground)))
urwid.display_common.AttrSpecError: Unrecognised color specification 'italics' in foreground (',italics')


Installed it yesterday. it worked fine. But today, got this issue.

using "toot curses" now.
