### ISSUE TITLE
Syntax error when using toot tui

### ISSUE THREAD

**Issue by popey** [ihabunek/toot#131]
I wanted to try the new tui interface but I get the following error. I tried deleting my config and re-authing, but I get the same issue. Any ideas what I'm doing wrong?

```
popey@localhost:~$ toot tui
Traceback (most recent call last):
  File "/bin/toot", line 11, in <module>
    load_entry_point('toot==0.24.0', 'console_scripts', 'toot')()
  File "/lib/python3.5/site-packages/toot/console.py", line 545, in main
    run_command(app, user, command_name, args)
  File "/lib/python3.5/site-packages/toot/console.py", line 527, in run_command
    return fn(app, user, parsed_args)
  File "/lib/python3.5/site-packages/toot/commands.py", line 330, in tui
    from .tui.app import TUI
  File "/lib/python3.5/site-packages/toot/tui/app.py", line 29
    ("pack", urwid.Text(('header', f' | {user.username}@{app.instance}'))),
                                                                      ^
SyntaxError: invalid syntax
```

**Comment by ihabunek** [comment]
Fixed, will be released in next version.

**Comment by popey** [comment]
Thanks for the prompt fix!
