### ISSUE TITLE
toot tui crashes with Python 3.8

### ISSUE THREAD

**Issue by ynakao** [ihabunek/toot#136]
After updated to Python 3.8 on Arch Linux, toot crashes while starting up `toot tui`.
I reinstalled toot from [AUR](https://aur.archlinux.org/packages/toot/), but no luck.

`toot timeline`, `toot whoami` and other commands also raise `Unknown error`.

```
Unknown error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/toot/tui/app.py", line 154, in _done
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/toot/tui/app.py", line 249, in _load_statuses
    data = next(self.timeline_generator)
  File "/usr/lib/python3.8/site-packages/toot/api.py", line 171, in _timeline_generator
    response = http.get(app, user, path, params)
  File "/usr/lib/python3.8/site-packages/toot/http.py", line 57, in get
    return process_response(response)
  File "/usr/lib/python3.8/site-packages/toot/http.py", line 45, in process_response
    raise ApiError(error)
toot.exceptions.ApiError: Unknown error
```

**Comment by ynakao** [comment]
Ohhh, this seems a server side fault. I only upgraded python related packages but ingored postgres packages in pacman.conf. toot works fine now after upgrading postgres and restarting them.

I really sorry for bothering you.

**Comment by ihabunek** [comment]
No problem, thanks for reporting.
