### ISSUE TITLE
TUI problems

### ISSUE THREAD

**Issue by whistlewright** [ihabunek/toot#137]
Just installed toot to my Debian 9 computer through apt. I can post. I can see my timeline but when I enter toot tui I get this:

james@kensington:~$ toot tui
Traceback (most recent call last):
  File "/usr/bin/toot", line 11, in <module>
    load_entry_point('toot==0.23.1', 'console_scripts', 'toot')()
  File "/usr/lib/python3/dist-packages/toot/console.py", line 545, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 527, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 330, in tui
    from .tui.app import TUI
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 26
    ("pack", urwid.Text(('header', f' | {user.username}@{app.instance}'))),
                                                                      ^
SyntaxError: invalid syntax

So while I do have some functionality I am not sure I am getting the wow factor.

**Comment by bill-auger** [comment]
with python 3.8, i needed to install python3 urwid
