### ISSUE TITLE
tui failure

### ISSUE THREAD

**Issue by githubgnulinux** [ihabunek/toot#159]
Command terminal input:
toot tui
Command terminal response output:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/toot/tui/app.py", line 158, in _done
    result = future.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/toot/tui/app.py", line 259, in _load_statuses
    return [self.make_status(s) for s in data]
  File "/usr/local/lib/python3.4/dist-packages/toot/tui/app.py", line 259, in <listcomp>
    return [self.make_status(s) for s in data]
  File "/usr/local/lib/python3.4/dist-packages/toot/tui/app.py", line 222, in make_status
    return Status(status_data, is_mine, self.app.instance)
  File "/usr/local/lib/python3.4/dist-packages/toot/tui/entities.py", line 50, in __init__
    self.created_at = parse_datetime(data["created_at"])
  File "/usr/local/lib/python3.4/dist-packages/toot/tui/utils.py", line 20, in parse_datetime
    return dttm.astimezone()

**Comment by ihabunek** [comment]
Fixed in 0.26.0 please upgrade.
