### ISSUE TITLE
Fatal error when running tui in Manjaro

### ISSUE THREAD

**Issue by dualhammers** [ihabunek/toot#160]
Grabbed Toot from the snap in Manjaro's pamac package manager. I was able to log-in successfully.

Afterwards I typed `toot tui` and this occured

```Traceback (most recent call last):
  File "/snap/toot/247/bin/toot", line 11, in <module>
    load_entry_point('toot==0.25.2', 'console_scripts', 'toot')()
  File "/snap/toot/247/lib/python3.5/site-packages/toot/console.py", line 545, in main
    run_command(app, user, command_name, args)
  File "/snap/toot/247/lib/python3.5/site-packages/toot/console.py", line 527, in run_command
    return fn(app, user, parsed_args)
  File "/snap/toot/247/lib/python3.5/site-packages/toot/commands.py", line 330, in tui
    from .tui.app import TUI
  File "/snap/toot/247/lib/python3.5/site-packages/toot/tui/__init__.py", line 1, in <module>
    from urwid.command_map import command_map
  File "/snap/toot/247/lib/python3.5/site-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/snap/toot/247/lib/python3.5/site-packages/urwid/widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/snap/toot/247/lib/python3.5/site-packages/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/snap/toot/247/lib/python3.5/site-packages/urwid/util.py", line 58, in detect_encoding
    locale.setlocale(locale.LC_ALL, initial)
  File "/snap/toot/247/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting```

**Comment by basedtho** [comment]
what's your locale?

show the output of `locale`

**Comment by mgiagante** [comment]
I'm having the same problem in Ubuntu
```
$ uname -a
Linux mg-UX360UAK 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
My output for `locale` is as follows:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=es_AR.UTF-8
LC_TIME=es_AR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=es_AR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=es_AR.UTF-8
LC_NAME=es_AR.UTF-8
LC_ADDRESS=es_AR.UTF-8
LC_TELEPHONE=es_AR.UTF-8
LC_MEASUREMENT=es_AR.UTF-8
LC_IDENTIFICATION=es_AR.UTF-8
LC_ALL=

```

**Comment by dualhammers** [comment]
> what's your locale?
> 
> show the output of `locale`

```
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.utf8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.utf8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

Update, I restarted and have not had the same issues.

**Comment by Rostiger** [comment]
I'm getting the same error, even after restarting the system.
Here's the content of my locale:
> LANG=en_US.UTF-8
>LANGUAGE=
>
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC=de_AT.UTF-8
> LC_TIME=de_AT.UTF-8
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY=de_AT.UTF-8
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER=de_AT.UTF-8
> LC_NAME=de_AT.UTF-8
> LC_ADDRESS=de_AT.UTF-8
> LC_TELEPHONE=de_AT.UTF-8
> LC_MEASUREMENT=de_AT.UTF-8
> LC_IDENTIFICATION=de_AT.UTF-8
> LC_ALL=
>

**Comment by fossdd** [comment]
How did you installed that?

@dualhammers did that with `snap` and the others. Probebly it's a issue with snap. snap has often issues like that.

I'm using that on Manjaro installed with `pip` and works fine.

`locale`
```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```
