### ISSUE TITLE
Breaking upgrading from 0.8 to 0.12

### ISSUE THREAD

**Issue by chaica** [ihabunek/toot#17]
Toot breaks while upgrading from 0.8 to 0.12 with pip. The system is Debian Jessie.

```
# pip3 install toot --upgrade
Downloading/unpacking toot from https://pypi.python.org/packages/6f/cc/179576a3765782400e19f3c2d199c3e17f25f3c643b71fa9069b2e5ecc21/toot-0.12.0-py2.py3-none-any.whl#md5=af915604fcf89d8d2b09ad5a160449ca
  Downloading toot-0.12.0-py2.py3-none-any.whl
Requirement already up-to-date: future>=0.16 in /usr/local/lib/python3.4/dist-packages/future-0.16.0-py3.4.egg (from toot)
Downloading/unpacking beautifulsoup4>=4.5.0,<5.0 from https://pypi.python.org/packages/9e/d4/10f46e5cfac773e22707237bfcd51bbffeaf0a576b0a847ec7ab15bd7ace/beautifulsoup4-4.6.0-py3-none-any.whl#md5=f6becf1889e5697734cc98798d2f0111 (from toot)
  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB): 86kB downloaded
Downloading/unpacking requests>=2.13,<3.0 from https://pypi.python.org/packages/29/b9/d26a6ab2ee178415ab8c0c591d2a1eb782a50c42a417ae390055f86a63c1/requests-2.17.3-py2.py3-none-any.whl#md5=66a7f010b985631e768485af6f3c61df (from toot)
  Downloading requests-2.17.3-py2.py3-none-any.whl (87kB): 87kB downloaded
Downloading/unpacking certifi>=2017.4.17 (from requests>=2.13,<3.0->toot)
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB): 375kB downloaded
Downloading/unpacking idna>=2.5,<2.6 (from requests>=2.13,<3.0->toot)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking urllib3>=1.21.1,<1.22 (from requests>=2.13,<3.0->toot)
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB): 131kB downloaded
Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests>=2.13,<3.0->toot)
  Downloading chardet-3.0.3-py2.py3-none-any.whl (133kB): 133kB downloaded
Installing collected packages: toot, beautifulsoup4, requests, certifi, idna, urllib3, chardet
  Found existing installation: toot 0.8.0
    Uninstalling toot:
      Successfully uninstalled toot
  Found existing installation: beautifulsoup4 4.5.3
    Uninstalling beautifulsoup4:
      Successfully uninstalled beautifulsoup4
  Found existing installation: requests 2.13.0
    Uninstalling requests:
      Successfully uninstalled requests
  Found existing installation: urllib3 1.9.1
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: chardet 2.3.0
    Not uninstalling chardet at /usr/lib/python3/dist-packages, owned by OS
Successfully installed toot beautifulsoup4 requests certifi idna urllib3 chardet
Cleaning up...
# 
$ echo "test\n\ntest" | toot post
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (toot 0.12.0 (/usr/local/lib/python3.4/dist-packages), Requirement.parse('toot==0.8.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/toot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: toot==0.8.0
```

Trying to uninstall / install does not solve the issue:
```
# pip3 uninstall toot
Uninstalling toot:
  /usr/local/lib/python3.4/dist-packages/toot-0.12.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.4/dist-packages/toot-0.12.0.dist-info/METADATA
  /usr/local/lib/python3.4/dist-packages/toot-0.12.0.dist-info/RECORD
  /usr/local/lib/python3.4/dist-packages/toot-0.12.0.dist-info/WHEEL
  /usr/local/lib/python3.4/dist-packages/toot-0.12.0.dist-info/entry_points.txt
  /usr/local/lib/python3.4/dist-packages/toot-0.12.0.dist-info/metadata.json
  /usr/local/lib/python3.4/dist-packages/toot-0.12.0.dist-info/top_level.txt
  /usr/local/lib/python3.4/dist-packages/toot/__init__.py
  /usr/local/lib/python3.4/dist-packages/toot/__pycache__/__init__.cpython-34.pyc
  /usr/local/lib/python3.4/dist-packages/toot/__pycache__/api.cpython-34.pyc
  /usr/local/lib/python3.4/dist-packages/toot/__pycache__/app.cpython-34.pyc
  /usr/local/lib/python3.4/dist-packages/toot/__pycache__/commands.cpython-34.pyc
  /usr/local/lib/python3.4/dist-packages/toot/__pycache__/config.cpython-34.pyc
  /usr/local/lib/python3.4/dist-packages/toot/__pycache__/console.cpython-34.pyc
  /usr/local/lib/python3.4/dist-packages/toot/__pycache__/output.cpython-34.pyc
  /usr/local/lib/python3.4/dist-packages/toot/__pycache__/utils.cpython-34.pyc
  /usr/local/lib/python3.4/dist-packages/toot/api.py
  /usr/local/lib/python3.4/dist-packages/toot/app.py
  /usr/local/lib/python3.4/dist-packages/toot/commands.py
  /usr/local/lib/python3.4/dist-packages/toot/config.py
  /usr/local/lib/python3.4/dist-packages/toot/console.py
  /usr/local/lib/python3.4/dist-packages/toot/output.py
  /usr/local/lib/python3.4/dist-packages/toot/utils.py
Proceed (y/n)? y
  Successfully uninstalled toot
# pip3 install toot --upgrade
Downloading/unpacking toot
  Downloading toot-0.12.0-py2.py3-none-any.whl
Requirement already up-to-date: beautifulsoup4>=4.5.0,<5.0 in /usr/local/lib/python3.4/dist-packages (from toot)
Requirement already up-to-date: future>=0.16 in /usr/local/lib/python3.4/dist-packages/future-0.16.0-py3.4.egg (from toot)
Requirement already up-to-date: requests>=2.13,<3.0 in /usr/local/lib/python3.4/dist-packages (from toot)
Installing collected packages: toot
Successfully installed toot
Cleaning up...
$ echo "test\n\ntest" | toot post
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (toot 0.12.0 (/usr/local/lib/python3.4/dist-packages), Requirement.parse('toot==0.8.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/toot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: toot==0.8.0
```

Let me know if you need more information.

Cheers,
Carl

**Comment by chaica** [comment]
I was able to fix the situation by removing all files related to toot in /usr/local/bin/python3.4/dist-packages/ and using the version in the current Github repository (git clone, python3 setup.py install).

**Comment by ihabunek** [comment]
Not sure why this happened, please report if it happens again. I hope you can use the debian or openbsd packages which are now available to get around using pip to install.
