### ISSUE TITLE
Toot TUI crashes on launch

### ISSUE THREAD

**Issue by Akselmo** [ihabunek/toot#192]
When I try to launch toot tui it crashes. Other toot commands work, even toot curses. I had no problem before, I don't know what changed in my system to make this happen.

Stacktrace:

```
akseli@akseli-kubuntu:~$ toot tui
Traceback (most recent call last):
  File "/usr/bin/toot", line 11, in <module>
    load_entry_point('toot==0.27.0', 'console_scripts', 'toot')()
  File "/usr/lib/python3/dist-packages/toot/console.py", line 550, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 532, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 338, in tui
    TUI.create(app, user).run()
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 78, in create
    loop = urwid.MainLoop(
  File "/home/akseli/.local/lib/python3.9/site-packages/urwid/main_loop.py", line 114, in __init__
    screen.register_palette(palette)
  File "/home/akseli/.local/lib/python3.9/site-packages/urwid/display_common.py", line 778, in register_palette
    self.register_palette_entry(*item)
  File "/home/akseli/.local/lib/python3.9/site-packages/urwid/display_common.py", line 845, in register_palette_entry
    basic = AttrSpec(foreground, background, 16)
  File "/home/akseli/.local/lib/python3.9/site-packages/urwid/display_common.py", line 489, in __init__
    self.foreground = fg
  File "/home/akseli/.local/lib/python3.9/site-packages/urwid/display_common.py", line 577, in _set_foreground
    raise AttrSpecError(("Unrecognised color specification %s" +
urwid.display_common.AttrSpecError: Unrecognised color specification 'italics'in foreground (',italics')

```
My system info

```
Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-34-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15,6 GiB of RAM
Graphics Processor: AMD Radeon ™ RX 480 Graphics
```

**Comment by Wittionary** [comment]
Looks like `toot` is interpreting italics as a color. 
>Unrecognised color specification 'italics'in foreground (',italics')

Do you use italics in your prompt?

**Comment by Akselmo** [comment]
I unfortunately do not remember since I don't have the same setup anymore. I think I used nerd fonts: https://www.nerdfonts.com/

**Comment by Wittionary** [comment]
Did your issue go away with the newer setup?

**Comment by Akselmo** [comment]
Yup, so it seems!

Here's my current setup:

```
Operating System: Fedora Linux 36
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.17.9-300.fc36.x86_64 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15,6 GiB of RAM
Graphics Processor: AMD DIMGREY_CAVEFISH
```
