### ISSUE TITLE
Crash on TUI 

### ISSUE THREAD

**Issue by communistkiro** [ihabunek/toot#197]
Recent install of toot on x86-64, musl, void linux.  

Error is `Loading statuses...time data '' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'`

The full exception output:
```
Traceback (most recent call last):
  File "/sbin/toot", line 33, in <module>
    sys.exit(load_entry_point('toot==0.27.0', 'console_scripts', 'toot')())
  File "/usr/lib/python3.10/site-packages/toot/console.py", line 550, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3.10/site-packages/toot/console.py", line 532, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3.10/site-packages/toot/commands.py", line 338, in tui
    TUI.create(app, user).run()
  File "/usr/lib/python3.10/site-packages/toot/tui/app.py", line 116, in run
    self.loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/lib/python3.10/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 519, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 565, in unhandled_input
    return self._unhandled_input(input)
  File "/usr/lib/python3.10/site-packages/toot/tui/app.py", line 512, in unhandled_input
    self.show_exception(self.exception)
  File "/usr/lib/python3.10/site-packages/toot/tui/app.py", line 337, in show_exception
    widget=ExceptionStackTrace(exception),
  File "/usr/lib/python3.10/site-packages/toot/tui/overlays.py", line 40, in __init__
    lines = traceback.format_exception(etype=type(ex), value=ex, tb=ex.__traceback__)
TypeError: format_exception() got an unexpected keyword argument 'etype'
```

**Comment by communistkiro** [comment]
Oookay, tried it again today, just because nobody'd witten here, and it popped up? Maybe it's an error only when one's home timeline is still void as mine was yesterday?
