### ISSUE TITLE
Feature request: add support for the new 'edit' mode in Mastodon 4.x

### ISSUE THREAD

**Issue by mig5** [ihabunek/toot#224]
Mastodon 4.x now has the ability to edit a toot - this is distinct from the 'delete and rewrite' feature (which also still remains).

It would be great if Toot supported the 'Edit' option if the instance one's using supports it.

**Comment by mig5** [comment]
I am not even on the right Github project! :) I thought this was the Toot IOS app, haha. Sorry. Feel free to actually delete the issue.

**Comment by ihabunek** [comment]
The issue makes perfect sense for this toot app as well. Thanks! :⁠-⁠)

**Comment by ruario** [comment]
Looking forward to this

**Comment by danschwarz** [comment]
Just posted a patch in the mailing list to support this in command line mode. Basic feature is working. Media attachments don't seem to work yet, But then, they don't seem to work for regular posts, either ¯\_(ツ)_/¯.

**Comment by ihabunek** [comment]
Media upload doesn't work? :thinking:

**Comment by danschwarz** [comment]
Here's what I'm seeing when I try to post a .jpg  (this is 0.28.0 as packaged in my Ubuntu distro; not using master branch here)

`dschwarz@mini:~$ toot post -m Great-Sphinx-of-Giza-pyramid-background-Khafre.jpg
Uploading media: Great-Sphinx-of-Giza-pyramid-background-Khafre.jpg
Traceback (most recent call last):
  File "/usr/bin/toot", line 33, in <module>
    sys.exit(load_entry_point('toot==0.28.0', 'console_scripts', 'toot')())
  File "/usr/lib/python3/dist-packages/toot/console.py", line 560, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 542, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 103, in post
    args.text = "\n".join(m['text_url'] for m in uploaded_media)
TypeError: sequence item 0: expected str instance, NoneType found`

**Comment by bruceleerabbit** [comment]
What is the practical difference?  The web client for the node I’m on does not offer “edit” but it offers “delete & redraft”. When I do that, it really is simply doing a delete & redraft which breaks the thread & if it’s a poll votes are lost.

The abandoned _tootle_ app offers the “edit” feature, but I think that still has the same thread-breaking effect. If that’s still the case with whatever the API offers for editing, then what’s the benefit?

**Comment by strk** [comment]
I've had my minion provide a PR for this: #578 (let me know if you do not welcome such kind of contributions)
