### ISSUE TITLE
Toot TUI crash on login. Toot works.

### ISSUE THREAD

**Issue by ubuntuperonista** [ihabunek/toot#248]
While I'm able to use toot with my Pleroma account, toot TUI crash at login.

I'm using toot version 0.28.0 on OpenBSD 7.1, with Python 3.9.15. I logged into my Pleroma account using toot_cli, and I'm able to use toot from CLI. But my toot TUI crash, while showing the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/toot/tui/app.py", Line 159, in _done
    result = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", Line 439, in result
    return self.     get result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", Line 391, in get_result
    raise self. exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", Line 58, in run
    result = self.fn(*self.kwarg)
  File "/usr/local/lib/python3.9/site-packages/toot/tui/app.py", Line 274, in load_statuses
     date = next(self-timeline_generator)
   File "/usr/local/lib/python3.9/site-plackates/toot/api.py", Line 179, in timeline_generator
    response = http.get(app, user, path, params)
  File "/usr/local/lib/python3.9/site-packages/toot/http.py", Line 57, in get
    return process_response(response)
  File "/usr/local/lib/python3.9/site-packages/toot/http.py", Line 45, in process response
    raise ApiError(error)
toot.exceptions.ApiError: unknown error

```
I tried deleting my ~/.config/toot/config.json file and was able to recreate a new toot token sucessfully, but the issue remains. I'm under the impression it has something to do with the python3.9, but others users in the system were able to login into their pleroma accounts without this issue.

The issue #144 may also be related, as my account has large toots (5000 char max in Pleroma).

**Comment by ubuntuperonista** [comment]
Using toot TUI with Python 3.10.6 on Ubuntu 22.04LTS i got an
"**TypeError: format_exception() got an unexpected keyword argument 'etype'`**" error:

`Traceback (most recent call last):
  File "/usr/bin/toot", line 33, in <module>
    sys.exit(load_entry_point('toot==0.28.0', 'console_scripts', 'toot')())
  File "/usr/lib/python3/dist-packages/toot/console.py", line 560, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 542, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 347, in tui
    TUI.create(app, user).run()
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 116, in run
    self.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 519, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 565, in unhandled_input
    return self._unhandled_input(input)
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 512, in unhandled_input
    self.show_exception(self.exception)
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 337, in show_exception
    widget=ExceptionStackTrace(exception),
  File "/usr/lib/python3/dist-packages/toot/tui/overlays.py", line 40, in __init__
    lines = traceback.format_exception(etype=type(ex), value=ex, tb=ex.__traceback__)
TypeError: format_exception() got an unexpected keyword argument 'etype'`
