### ISSUE TITLE
Errors if piping output

### ISSUE THREAD

**Issue by matthiasbeyer** [ihabunek/toot#29]
```
toot timeline | head -n 15
```

results in

```
Traceback (most recent call last):
  File "/nix/store/1qxdqk0jgwmja1g263913lz7s8flndkn-toot-0.13.0/bin/.toot-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/1qxdqk0jgwmja1g263913lz7s8flndkn-toot-0.13.0/lib/python2.7/site-packages/toot/console.py", line 301, in main
    run_command(app, user, command_name, args)
  File "/nix/store/1qxdqk0jgwmja1g263913lz7s8flndkn-toot-0.13.0/lib/python2.7/site-packages/toot/console.py", line 278, in run_command
    return fn(app, user, parsed_args)
  File "/nix/store/1qxdqk0jgwmja1g263913lz7s8flndkn-toot-0.13.0/lib/python2.7/site-packages/toot/commands.py", line 173, in timeline
    print_out("─" * 31 + "┬" + "─" * 88)
  File "/nix/store/1qxdqk0jgwmja1g263913lz7s8flndkn-toot-0.13.0/lib/python2.7/site-packages/toot/output.py", line 49, in print_out
    print(*args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-119: ordinal not in range(128)
```

**Comment by ihabunek** [comment]
@matthiasbeyer I decided to drop support for python2, unicode support is one of the reasons. Could you please check if this happens with py3 and the latest version?

**Comment by matthiasbeyer** [comment]
Pushed an update to nixpkgs which updates toot to 0.16.2 (which fixes this issue for me).

**Comment by ihabunek** [comment]
@matthiasbeyer That's cool. Would you mind contributing instructions for installation on nixos?
