### ISSUE TITLE
KeyError: 'edited_at' when running 'toot tui' on toot 0.34.0

### ISSUE THREAD

**Issue by highvoltage** [ihabunek/toot#309]
Hi, when running 'toot tui' on Debian unstable (toot v0.34.0), I get the following error:

"""
Traceback (most recent call last):
  File "/usr/bin/toot", line 33, in <module>
    sys.exit(load_entry_point('toot==0.34.0', 'console_scripts', 'toot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/toot/console.py", line 693, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 675, in run_command
    return fn(app, user, parsed_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 420, in tui
    TUI.create(app, user, args).run()
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 121, in run
    self.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 173, in cb
    callback(self, user_data)
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 167, in <lambda>
    self.loop.set_alarm_in(0, lambda *args: done_callback(result))
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 304, in _done_initial
    self.timeline = self.build_timeline(timeline_name, statuses, local)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 250, in build_timeline
    timeline = Timeline(name, statuses, self.can_translate, self.followed_tags)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/toot/tui/timeline.py", line 50, in __init__
    self.status_list = self.build_status_list(statuses, focus=focus)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/toot/tui/timeline.py", line 82, in build_status_list
    items = [self.build_list_item(status) for status in statuses]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/toot/tui/timeline.py", line 82, in <listcomp>
    items = [self.build_list_item(status) for status in statuses]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/toot/tui/timeline.py", line 89, in build_list_item
    item = StatusListItem(status)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/toot/tui/timeline.py", line 430, in __init__
    edited = status.data["edited_at"]
             ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'edited_at'
"""

Is this a bug in toot?

thanks!

-Jonathan

**Comment by ihabunek** [comment]
Most probably a problem when connecting to mastodon instances running version older than 4. That should be changed to ` status.data.get("edited_at")`. Travelling but I'll try to fix it asap.

**Comment by ihabunek** [comment]
Fixed in https://github.com/ihabunek/toot/releases/tag/0.34.1
