### ISSUE TITLE
toot curses crashes when display some boosts

### ISSUE THREAD

**Issue by veer66** [ihabunek/toot#33]
By displaying this boost ![screenshot-2017-12-10 sakamoto social](https://user-images.githubusercontent.com/370688/33806032-6a7b479e-ddf4-11e7-9836-456d16f6034f.png) from https://social.sakamoto.gq/users/eal makes toot curses crashed.

The error message is as follow:
`````
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vee/Develop/free/toot/toot/console.py", line 307, in main
    run_command(app, user, command_name, args)
  File "/home/vee/Develop/free/toot/toot/console.py", line 283, in run_command
    return fn(app, user, parsed_args)
  File "/home/vee/Develop/free/toot/toot/commands.py", line 181, in curses
    TimelineApp(generator).run()
  File "/home/vee/Develop/free/toot/toot/app.py", line 46, in run
    curses.wrapper(self._wrapped_run)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/vee/Develop/free/toot/toot/app.py", line 65, in _wrapped_run
    self.loop()
  File "/home/vee/Develop/free/toot/toot/app.py", line 80, in loop
    self.select_next()
  File "/home/vee/Develop/free/toot/toot/app.py", line 105, in select_next
    self.redraw_after_selection_change(old_index, new_index)
  File "/home/vee/Develop/free/toot/toot/app.py", line 114, in redraw_after_selection_change
    self.draw_status_details(self.right, new_status)
  File "/home/vee/Develop/free/toot/toot/app.py", line 219, in draw_status_details
    window.addstr(y, 2, status['url'])
TypeError: expect bytes or str, got NoneType

`````

**Comment by ihabunek** [comment]
Thanks @veer66. Releasing in a sec.
