### ISSUE TITLE
toot tui crashes with Python 3.11.3

### ISSUE THREAD

**Issue by swimm3r** [ihabunek/toot#394]
toot tui
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urwid/font.py", line 243, in render
    canv = TextCanvas(byte_lines, None, character_set_lines, maxcol=width, check_width=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/canvas.py", line 402, in __init__
    raise CanvasError(f"Attribute extends beyond text \n{text[i]!r}\n{attr[i]!r}" )
urwid.canvas.CanvasError: Attribute extends beyond text 
b'  \xe2\x94\x82   '
[(None, 16)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/toot", line 33, in <module>
    sys.exit(load_entry_point('toot==0.38.1', 'console_scripts', 'toot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/toot/console.py", line 961, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3.11/site-packages/toot/console.py", line 943, in run_command
    return fn(app, user, parsed_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/toot/commands.py", line 571, in tui
    TUI.create(app, user, args).run()
  File "/usr/lib/python3.11/site-packages/toot/tui/app.py", line 149, in run
    self.loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 320, in run
    self._run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 423, in _run
    self.event_loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/asyncio_loop.py", line 191, in run
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/asyncio_loop.py", line 78, in wrapper
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 621, in entering_idle
    self.draw_screen()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 635, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 1567, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/decoration.py", line 1029, in render
    canv = self._original_widget.render((maxcol,), focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 2147, in render
    canv = w.render((maxcol,), focus=focus and item_focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/decoration.py", line 725, in render
    canv = self._original_widget.render((), focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/graphics.py", line 102, in render
    c = self.font.render(ch)
        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/font.py", line 245, in render
    raise CanvasError(
  File "/usr/lib/python3.11/site-packages/urwid/font.py", line 243, in render
    canv = TextCanvas(byte_lines, None, character_set_lines, maxcol=width, check_width=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/canvas.py", line 402, in __init__
    raise CanvasError(f"Attribute extends beyond text \n{text[i]!r}\n{attr[i]!r}" )
urwid.canvas.CanvasError: Failed render of 'T' from line ['┌─┬─┐ ', '  │   ', '  │   ', '  │   ', '  ┴   ', '      ']:
Thin6x6Font():
  6
  [   '\n'
    "000000111111222222333333444444555555666666777777888888999999''\n"
    '┌───┐   ┐   ┌───┐ ┌───┐    ┐  ┌───  ┌───  ┌───┐ ┌───┐ ┌───┐ │\n'
    '│   │   │       │     │ ┌  │  │     │         │ │   │ │   │\n'
    '│ / │   │   ┌───┘    ─┤ └──┼─ └───┐ ├───┐     ┼ ├───┤ └───┤\n'
    '│   │   │   │         │    │      │ │   │     │ │   │     │\n'
    '└───┘   ┴   └───  └───┘    ┴   ───┘ └───┘     ┴ └───┘  ───┘\n'
    '\n',
    '\n'
    '!!   """######$$$$$$%%%%%%&&&&&&((()))******++++++\n'
    '│    ││  ┌ ┌  ┌─┼─┐ ┌┐  /  ┌─┐   / \\\n'
    '│       ─┼─┼─ │ │   └┘ /   │ │  │   │  \\ /    │\n'
    '│        │ │  └─┼─┐   /   ┌─\\┘  │   │ ──X── ──┼──\n'
    '│       ─┼─┼─   │ │  / ┌┐ │  \\, │   │  / \\    │\n'
    '.        ┘ ┘  └─┼─┘ /  └┘ └───\\  \\ /\n'
    '\n',
    '\n'
    ',,-----..//////::;;<<<<=====>>>>??????@@@@@@\n'
    '             /                  ┌───┐ ┌───┐\n'
    '            /  . .   / ──── \\       │ │┌──┤\n'
    '  ────     /        /        \\    ┌─┘ ││  │\n'
    '          /    . ,  \\  ────  /    │   │└──┘\n'
    ',      . /           \\      /     .   └───┘\n'
    '\n',
    '\n'
    '[[\\\\\\\\\\\\]]^^^____``{{||}}~~~~~~\n'
    '┌ \\     ┐ /\\     \\ ┌ │ ┐\n'
    '│  \\    │          │ │ │ ┌─┐\n'
    '│   \\   │          ┤ │ ├   └─┘\n'
    '│    \\  │          │ │ │\n'
    '└     \\ ┘    ────  └ │ ┘\n'
    '\n',
    '\n'
    'AAAAAABBBBBBCCCCCCDDDDDDEEEEEEFFFFFFGGGGGGHHHHHHIIJJJJJJ\n'
    '┌───┐ ┬───┐ ┌───┐ ┬───┐ ┬───┐ ┬───┐ ┌───┐ ┬   ┬ ┬     ┬\n'
    '│   │ │   │ │     │   │ │     │     │     │   │ │     │\n'
    '├───┤ ├───┤ │     │   │ ├──   ├──   │ ──┬ ├───┤ │     │\n'
    '│   │ │   │ │     │   │ │     │     │   │ │   │ │ ┬   │\n'
    '┴   ┴ ┴───┘ └───┘ ┴───┘ ┴───┘ ┴     └───┘ ┴   ┴ ┴ └───┘\n'
    '\n',
    '\n'
    'KKKKKKLLLLLLMMMMMMNNNNNNOOOOOOPPPPPPQQQQQQRRRRRRSSSSSS\n'
    '┬   ┬ ┬     ┌─┬─┐ ┬─┐ ┬ ┌───┐ ┬───┐ ┌───┐ ┬───┐ ┌───┐\n'
    '│ ┌─┘ │     │ │ │ │ │ │ │   │ │   │ │   │ │   │ │\n'
    '├─┴┐  │     │ │ │ │ │ │ │   │ ├───┘ │   │ ├─┬─┘ └───┐\n'
    '│  └┐ │     │   │ │ │ │ │   │ │     │  ┐│ │ └─┐     │\n'
    '┴   ┴ ┴───┘ ┴   ┴ ┴ └─┴ └───┘ ┴     └──┼┘ ┴   ┴ └───┘\n'
    '                                       └\n',
    '\n'
    'TTTTTTUUUUUUVVVVVVWWWWWWXXXXXXYYYYYYZZZZZZ\n'
    '┌─┬─┐ ┬   ┬ ┬   ┬ ┬   ┬ ┬   ┬ ┬   ┬ ┌───┐\n'
    '  │   │   │ │   │ │   │ └┐ ┌┘ │   │   ┌─┘\n'
    '  │   │   │ │   │ │ │ │  ├─┤  └─┬─┘  ┌┘\n'
    '  │   │   │ └┐ ┌┘ │ │ │ ┌┘ └┐   │   ┌┘\n'
    '  ┴   └───┘  └─┘  └─┴─┘ ┴   ┴   ┴   └───┘\n'
    '\n',
    '\n'
    'aaaaaabbbbbbccccccddddddeeeeeefffgggggghhhhhhiijjj\n'
    '                              ┌─┐\n'
    '      │               │       │        │     .  .\n'
    '┌───┐ ├───┐ ┌───┐ ┌───┤ ┌───┐ ┼  ┌───┐ ├───┐ ┐  ┐\n'
    '┌───┤ │   │ │     │   │ ├───┘ │  │   │ │   │ │  │\n'
    '└───┴ └───┘ └───┘ └───┘ └───┘ ┴  └───┤ ┴   ┴ ┴  │\n'
    '                                 └───┘         ─┘\n',
    '\n'
    'kkkkkkllmmmmmmnnnnnnooooooppppppqqqqqqrrrrrssssss\n'
    '\n'
    '│     │\n'
    '│ ┌─  │ ┬─┬─┐ ┬───┐ ┌───┐ ┌───┐ ┌───┐ ┬──┐ ┌───┐\n'
    '├─┴┐  │ │ │ │ │   │ │   │ │   │ │   │ │    └───┐\n'
    '┴  └─ └ ┴   ┴ ┴   ┴ └───┘ ├───┘ └───┤ ┴    └───┘\n'
    '                          │         │\n',
    '\n'
    'ttttuuuuuuvvvvvvwwwwwwxxxxxxyyyyyyzzzzzz\n'
    '\n'
    ' │\n'
    '─┼─ ┬   ┬ ┬   ┬ ┬   ┬ ─┐ ┌─ ┬   ┬ ────┬\n'
    ' │  │   │ └┐ ┌┘ │ │ │  ├─┤  │   │ ┌───┘\n'
    ' └─ └───┴  └─┘  └─┴─┘ ─┘ └─ └───┤ ┴────\n'
    '                            └───┘\n']
:Attribute extends beyond text 
b'  \xe2\x94\x82   '
[(None, 16)]

**Comment by danschwarz** [comment]
This is actually a defect in Urwid, please retest against the latest Urwid 2.2.1 (just released a few days ago; you may need to `pip uninstall urwid` / `pip reinstall urwid` to force the update.

Note that 2.2.1 may have introduced its own issues 🙄 If you find that the toot tui is "stalling" at startup, pressing a key should allow it to continue.

**Comment by swimm3r** [comment]
Retest, and works fine. Thank you.
Ticket can be closed.
