### ISSUE TITLE
Ability to pipe successfully

### ISSUE THREAD

**Issue by bignimbus** [ihabunek/toot#4]
To reproduce:

```bash
# any piped operation will produce this error
toot timeline | pbcopy
```

Produces the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/toot", line 9, in <module>
    load_entry_point('toot==0.7.0', 'console_scripts', 'toot')()
  File "/Library/Python/2.7/site-packages/toot/console.py", line 491, in main
    run_command(command, args)
  File "/Library/Python/2.7/site-packages/toot/console.py", line 459, in run_command
    return cmd_timeline(app, user, args)
  File "/Library/Python/2.7/site-packages/toot/console.py", line 218, in cmd_timeline
    print("─" * 31 + "┬" + "─" * 88)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-119: ordinal not in range(128)
```

* toot v. 0.7.0
* macOS v. 10.12.4
* python v. 2.7

**Comment by vext01** [comment]
Same here.

**Comment by ihabunek** [comment]
Hm, I'm on linux and unable to reproduce this. Could you please upgrade to `0.8.0` and check if it still happens? I did some improvements for unicode support recently.

**Comment by bignimbus** [comment]
@ihabunek same error in 0.8.0. Details:

```
Traceback (most recent call last):
  File "/usr/local/bin/toot", line 9, in <module>
    load_entry_point('toot==0.8.0', 'console_scripts', 'toot')()
  File "/Library/Python/2.7/site-packages/toot/console.py", line 202, in main
    run_command(app, user, command_name, args)
  File "/Library/Python/2.7/site-packages/toot/console.py", line 181, in run_command
    return fn(app, user, parsed_args)
  File "/Library/Python/2.7/site-packages/toot/commands.py", line 163, in timeline
    print("─" * 31 + "┬" + "─" * 88)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-119: ordinal not in range(128)
```

* toot v. 0.8.0
* macOS v. 10.12.4
* python v. 2.7

**Comment by bignimbus** [comment]
May I recommend encoding the output into valid markdown?  Markdown supports tables and then we'd be able to pipe into an app like [mdless](http://brettterpstra.com/projects/mdless/) for even nicer formatting.

**Comment by ihabunek** [comment]
I believe this was an issue with python 2, newer versions only support python 3. If this still occurs, please open a new issue. Thanks.
