### ISSUE TITLE
[bug] TUI fails to launch on FreeBSD

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [ihabunek/toot#443]
On my FreeBSD system, Toot fails to launch `toot tui`, both from the pypi version and the version shipped by pkg
Error:
```bash
tetra@poison:~ % toot tui --debug
Traceback (most recent call last):
  File "/usr/local/bin/toot", line 33, in <module>
    sys.exit(load_entry_point('toot==0.28.0', 'console_scripts', 'toot')())
  File "/home/tetra/.local/lib/python3.9/site-packages/toot/console.py", line 961, in main
    run_command(app, user, command_name, args)
  File "/home/tetra/.local/lib/python3.9/site-packages/toot/console.py", line 943, in run_command
    return fn(app, user, parsed_args)
  File "/home/tetra/.local/lib/python3.9/site-packages/toot/commands.py", line 668, in tui
    from .tui.app import TUI
  File "/home/tetra/.local/lib/python3.9/site-packages/toot/tui/__init__.py", line 1, in <module>
    from urwid.command_map import command_map
  File "/usr/local/lib/python3.9/site-packages/urwid/__init__.py", line 72, in <module>
    from urwid.version import __version__, __version_tuple__
ImportError: cannot import name '__version__' from 'urwid.version' (/usr/local/lib/python3.9/site-packages/urwid/version.py)
```

**Comment by lexiwinter** [comment]
this is [FreeBSD PR# 274411](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274411).  until it's fixed, the workaround is to build devel/py-urwid with devel/py-setuptools_scm7 instead of devel/py-setuptools_scm.

see also: [D39288](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274411) (upgrade of setuptools_scm to 8.x).

**Comment by ihabunek** [comment]
Closing as this is not a toot issue. Thanks @lexiwinter.
