### ISSUE TITLE
Apparent threading issue in toot 0.43.0 / Python 3.11 / Debian unstable

### ISSUE THREAD

**Issue by highvoltage** [ihabunek/toot#480]
Hi! I'm updating toot in Debian unstable, and upon running 'toot tui', I get the the following tracebacks:

"""
Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1560, in _shutdown
    atexit_call()
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.11/threading.py", line 1119, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.11/threading.py", line 1139, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"""

The TUI seems to work fine otherwise, it just prints these a few times during startup.

**Comment by ihabunek** [comment]
@danschwarz Could you please have a look if you have free time?

**Comment by danschwarz** [comment]
@ihabunek I will try. My main dev environment is Ubuntu 22.04, not Debian unstable, so I'll have to see if I can spin up a VM with that.

@highvoltage What specfic version of Urwid are you using? They have revised some of their thread handling code over the past several months.
