### ISSUE TITLE
error to the first run

### ISSUE THREAD

**Issue by mathdatech** [ihabunek/toot#49]
Hello, 
when I want to run toot, I've a error, but I don't understand why. they have the same error on my 3 computers (Fedora 27) :

```
mathieu  ~  toot
Traceback (most recent call last):
  File "/usr/bin/toot", line 7, in <module>
    from toot.console import main
  File "/usr/lib/python2.7/site-packages/toot/console.py", line 5, in <module>
    import logging
  File "/usr/lib/python2.7/site-packages/toot/logging.py", line 1, in <module>
    from logging import getLogger
ImportError: cannot import name getLogger
```
```
mathieu  ~  python
Python 2.7.14 (default, Jan 17 2018, 14:28:32) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

do you have a solution?

**Comment by joachimesque** [comment]
I got the same problem when I installed toot from pipy on macOS  10.13.4 High Sierra.

**Comment by mathdatech** [comment]
A update (of what ?) resolve my problem.
