### ISSUE TITLE
TUI: Crash when loading a specific account

### ISSUE THREAD

**Issue by ArthurHoaro** [ihabunek/toot#499]
It looks the same as [this issue](https://github.com/ihabunek/toot/issues/481) (solved), but for an account and not a post.
I'm guessing it's because of accented characters in the profile/hashtags.

Account: @juliette@mastodon.green
From post: https://mastodon.green/@juliette/113039496315816199

```
 ➜ toot env         
toot 0.44.1
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Linux-5.15.0-119-generic-x86_64-with-glibc2.35
```

Stacktrace:
```
Traceback (most recent call last):
  File "/home/arthur/.local/bin/toot", line 8, in <module>
    sys.exit(cli())
  File "/home/arthur/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/arthur/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/arthur/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arthur/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arthur/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/arthur/.local/lib/python3.10/site-packages/toot/cli/__init__.py", line 124, in wrapped
    return f(get_context(), *args, **kwargs)
  File "/home/arthur/.local/lib/python3.10/site-packages/toot/cli/tui.py", line 73, in tui
    tui.run()
  File "/home/arthur/.local/lib/python3.10/site-packages/toot/tui/app.py", line 164, in run
    self.loop.run()
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/event_loop/main_loop.py", line 337, in run
    self._run()
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/event_loop/main_loop.py", line 439, in _run
    self.event_loop.run()
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/event_loop/asyncio_loop.py", line 235, in run
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/event_loop/asyncio_loop.py", line 114, in _entering_idle
    callback()
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/event_loop/main_loop.py", line 650, in entering_idle
    self.draw_screen()
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/event_loop/main_loop.py", line 667, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/frame.py", line 481, in render
    body = self.body.render((maxcol, maxrow - ftrim - htrim), focus and self.focus_part == "body")
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/overlay.py", line 907, in render
    top_c = self.top_w.render(self.top_w_size(real_size, left, right, top, bottom), focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 711, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/pile.py", line 873, in render
    canv = w.render(w_size, focus=focus and item_focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/columns.py", line 1026, in render
    w.render(w_size, focus=focus and self.focus_position == i),
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/listbox.py", line 754, in render
    canvas = widget.render((maxcol,))
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/pile.py", line 873, in render
    canv = w.render(w_size, focus=focus and item_focus)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 113, in cached_render
    validate_size(self, size, canv)
  File "/home/arthur/.local/lib/python3.10/site-packages/urwid/widget/widget.py", line 92, in validate_size
    raise WidgetError(
urwid.widget.widget.WidgetError: Widget <TextEmbed fixed/flow widget 'slow living in denmark. interests include \uf8fe\uf8ff\uf8ff\uf8ff\uf8ff\uf8ff\uf8ff, \uf...d \uf8fe\uf8ff\uf8ff\uf8ff\uf8ff.\u2029she/her'> rendered (224 x 1) canvas when passed size (225,)!
```

**Comment by danschwarz** [comment]
please provide output of `toot diag` command.  I want to see what versions of urwidgets and urwid you are running.

**Comment by ArthurHoaro** [comment]
```
 ➜ toot diag        
## Toot Diagnostics

Current Date/Time: 2024-08-28 16:29:26 UTC
Toot version: 0.44.1
Platform: Linux-5.15.0-119-generic-x86_64-with-glibc2.35
Distro: Ubuntu 22.04.4 LTS
Python version: 3.10.12

Dependency versions:
 * beautifulsoup4: 4.10.0
 * click: 8.1.7
 * flake8: 7.0.0
 * pillow: 10.4.0
 * pytest: not installed
 * requests: 2.25.1
 * setuptools: 72.1.0
 * term-image: 0.7.2
 * tomlkit: 0.13.0
 * typing-extensions: 4.12.2
 * urwid: 2.6.15
 * urwidgets: 0.2.0
 * vermin: not installed
 * wcwidth: 0.2.5

Settings file path: /home/arthur/.config/toot/settings.toml
Config file path: /home/arthur/.config/toot/config.json
```

**Comment by danschwarz** [comment]
@AnonymouX47  this is with Urwidgets 0.2.0, any thoughts?

**Comment by AnonymouX47** [comment]
Hello!

I looked into the issue and found out it was due to the presence of the U+2029 (Paragraph Separator) codepoint in the user's bio (between "." and "she/her"), as I initially suspected. This is a really uncommon edge case but still deserves attention.

So, I dug further and realised the exception raised was due to the use of `urwid.Text.pack()` (which happens to be buggy with the use of Unicode line breaks; reported in https://github.com/urwid/urwid/issues/924) for width computation by `TextEmbed`.

I've now switched to using `urwid.calc_width()` instead and released [v0.2.1](https://github.com/AnonymouX47/urwidgets/releases/tag/v0.2.1). This issue should now be fixed with the new version.

Thank you very much. :smiley:

**Comment by wjjunyor** [comment]
Good afternoon. The issue prevails actually for unicode char \u2605 in displayname. 

`❯ toot whoami
Traceback (most recent call last):
File "/nix/store/wv3pzywxkh452l2g20x399k5shpiyngy-toot-0.47.1/bin/.toot-wrapped", line 9, in <module>
sys.exit(cli())
^^^^^
File "/nix/store/smb419x6dzn8yzlxls29zvr73cfj203x-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nix/store/smb419x6dzn8yzlxls29zvr73cfj203x-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/nix/store/smb419x6dzn8yzlxls29zvr73cfj203x-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nix/store/smb419x6dzn8yzlxls29zvr73cfj203x-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nix/store/smb419x6dzn8yzlxls29zvr73cfj203x-python3.12-click-8.1.7/lib/python3.12/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nix/store/wv3pzywxkh452l2g20x399k5shpiyngy-toot-0.47.1/lib/python3.12/site-packages/toot/cli/__init__.py", line 136, in wrapped
return f(get_context(), *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nix/store/wv3pzywxkh452l2g20x399k5shpiyngy-toot-0.47.1/lib/python3.12/site-packages/toot/cli/read.py", line 26, in whoami
print_account(account)
File "/nix/store/wv3pzywxkh452l2g20x399k5shpiyngy-toot-0.47.1/lib/python3.12/site-packages/toot/output.py", line 74, in print_account
click.echo(account_to_text(account, width))
File "/nix/store/smb419x6dzn8yzlxls29zvr73cfj203x-python3.12-click-8.1.7/lib/python3.12/site-packages/click/utils.py", line 318, in echo
file.write(out)  # type: ignore
^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2605' in position 44: ordinal not in range(256)
`
----------------

`❯ toot diag
## Toot Diagnostics

toot 0.47.1
Python 3.12.8
Linux-6.13.1-x86_64-with-glibc2.40
NixOS 25.05 (Warbler)

Dependencies:
* beautifulsoup4: 4.12.3
* click: 8.1.7
* pillow: 11.1.0
* requests: 2.32.3
* setuptools: not installed
* term-image: 0.7.2
* tomlkit: 0.13.2
* typing-extensions: 4.12.2
* urwid: 2.6.16
* urwidgets: 0.2.1
* wcwidth: 0.2.13

Settings file: not found

Config file: /W/Shared/WJR/.config/toot/config.json
`

**Comment by AnonymouX47** [comment]
@wjjunyor , your case is a very different, specifically having to do with character encoding.

Looks like an issue with your locale/environment settings.

You should create a new issue and include the output of the `locale` command in the same environment where you executed `toot`.

Thank you. :smiley:

- - -

@danschwarz I believe this issue should now be closed.
