### ISSUE TITLE
Crashes due to Unicode chars

### ISSUE THREAD

**Issue by Gumnos** [ihabunek/toot#68]
Trying both `toot curses` and `toot timeline` crash, both apparently due to Unicode characters in my timeline:

    tim@solo:~$ toot curses
    Traceback (most recent call last):                                             
      File "/usr/local/bin/toot", line 11, in <module>                             
        load_entry_point('toot==0.17.1', 'console_scripts', 'toot')()              
      File "/usr/local/lib/python3.6/site-packages/toot/console.py", line 338, in main
        run_command(app, user, command_name, args)                                 
      File "/usr/local/lib/python3.6/site-packages/toot/console.py", line 314, in run_command
        return fn(app, user, parsed_args)                                          
      File "/usr/local/lib/python3.6/site-packages/toot/commands.py", line 78, in curses
        TimelineApp(generator).run()                                               
      File "/usr/local/lib/python3.6/site-packages/toot/ui/app.py", line 228, in run
        curses.wrapper(self._wrapped_run)                                          
      File "/usr/local/lib/python3.6/curses/__init__.py", line 94, in wrapper      
        return func(stdscr, *args, **kwds)                                         
      File "/usr/local/lib/python3.6/site-packages/toot/ui/app.py", line 239, in _wrapped_run
        self.full_redraw()                                                         
      File "/usr/local/lib/python3.6/site-packages/toot/ui/app.py", line 328, in full_redraw
        self.left.draw_statuses(self.statuses, self.selected)                      
      File "/usr/local/lib/python3.6/site-packages/toot/ui/app.py", line 105, in draw_statuses
        self.draw_status_row(status, index, highlight, draw_divider)               
      File "/usr/local/lib/python3.6/site-packages/toot/ui/app.py", line 128, in draw_status_row
        draw_horizontal_divider(self.pad, offset + 3)                              
      File "/usr/local/lib/python3.6/site-packages/toot/ui/utils.py", line 7, in draw_horizontal_divider
        window.addstr(y, 0, line)                                                  
    _curses.error: addwstr() returned ERR              

    tim@solo:~$ toot timeline                                                      
    Traceback (most recent call last):                                             
      File "/usr/local/bin/toot", line 11, in <module>                             
        load_entry_point('toot==0.17.1', 'console_scripts', 'toot')()              
      File "/usr/local/lib/python3.6/site-packages/toot/console.py", line 338, in main
        run_command(app, user, command_name, args)                                 
      File "/usr/local/lib/python3.6/site-packages/toot/console.py", line 314, in run_command
        return fn(app, user, parsed_args)                                          
      File "/usr/local/lib/python3.6/site-packages/toot/commands.py", line 60, in timeline
        print_out("\u2500" * 31 + "\u252c" + "\u2500" * 88)                        
      File "/usr/local/lib/python3.6/site-packages/toot/output.py", line 49, in print_out
        print(*args, **kwargs)                                                     
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-119: ordinal not in range(128)

If the locale info makes a difference:

    tim@solo:~$ locale                                                             
    LANG=                                                                          
    LC_COLLATE="C"                                                                 
    LC_CTYPE="C"                                                                   
    LC_MONETARY="C"                                                                
    LC_NUMERIC="C"                                                                 
    LC_TIME="C"                                                                    
    LC_MESSAGES="C"                                                                
    LC_ALL=                 

and the output encoding and Python version info:

    $ python
    Python 3.6.4 (default, Mar 27 2018, 05:06:57)                                  
    [GCC 4.2.1 Compatible OpenBSD Clang 5.0.1 (tags/RELEASE_501/final)] on openbsd6
    Type "help", "copyright", "credits" or "license" for more information.         
    >>> import sys                                                                 
    >>> sys.stdout.encoding                                                        
    'US-ASCII'

**Comment by Gumnos** [comment]
Oh, and in case you need version information, it's `toot` from the OpenBSD package repos (0.17.1) from what I can tell:

    tim@solo:~$ pkg_info toot | head -1
    Information for inst:toot-0.17.1

**Comment by ihabunek** [comment]
It's a locale issue, I can reproduce if I set `LC_ALL=C`. That locale doesn't support unicode.

I don't have experience with locales on OpenBSD. On Debian I have something like this by default:

```
ihabunek@tomodachi:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

You can try running `locale -a` to see all installed locales. And toot should work if you run `LC_ALL="en_US.UTF-8" toot timeline` if that locale is installed.

Just don't hardcode `LC_ALL`, see how to properly change the locale on your system.
