### ISSUE TITLE
Install failed on OSX :( 

### ISSUE THREAD

**Issue by joereddington** [ihabunek/toot#76]
Installed with pip as per docs - installation claimed to go fine and then I get an error when running :( 

```
MacBook-Air:~ josephreddington$ pip install toot
Collecting toot
Requirement already satisfied: beautifulsoup4<5.0,>=4.5.0 in /Library/Python/2.7/site-packages (from toot) (4.6.0)
Collecting requests<3.0,>=2.13 (from toot)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0,>=2.13->toot)
  Using cached https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0,>=2.13->toot)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests<3.0,>=2.13->toot)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests<3.0,>=2.13->toot)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Installing collected packages: certifi, chardet, urllib3, idna, requests, toot
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/certifi'
Consider using the `--user` option or check the permissions.

MacBook-Air:~ josephreddington$ sudo !!
sudo pip install toot
The directory '/Users/josephreddington/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/josephreddington/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting toot
Requirement already satisfied: beautifulsoup4<5.0,>=4.5.0 in /Library/Python/2.7/site-packages (from toot) (4.6.0)
Collecting requests<3.0,>=2.13 (from toot)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 1.5MB/s 
Collecting certifi>=2017.4.17 (from requests<3.0,>=2.13->toot)
  Downloading https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl (147kB)
    100% |████████████████████████████████| 153kB 3.0MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0,>=2.13->toot)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 3.2MB/s 
Collecting urllib3<1.24,>=1.21.1 (from requests<3.0,>=2.13->toot)
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.0MB/s 
Collecting idna<2.8,>=2.5 (from requests<3.0,>=2.13->toot)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 3.8MB/s 
Installing collected packages: certifi, chardet, urllib3, idna, requests, toot
  Found existing installation: chardet 2.3.0
    Uninstalling chardet-2.3.0:
      Successfully uninstalled chardet-2.3.0
  Found existing installation: requests 2.7.0
    Uninstalling requests-2.7.0:
      Successfully uninstalled requests-2.7.0
Successfully installed certifi-2018.8.24 chardet-3.0.4 idna-2.7 requests-2.19.1 toot-0.19.0 urllib3-1.23
MacBook-Air:~ josephreddington$ toot login
Traceback (most recent call last):
  File "/usr/local/bin/toot", line 7, in <module>
    from toot.console import main
  File "/Library/Python/2.7/site-packages/toot/console.py", line 5, in <module>
    import logging
  File "/Library/Python/2.7/site-packages/toot/logging.py", line 1, in <module>
    from logging import getLogger
ImportError: cannot import name getLogger
```

**Comment by nloadholtes** [comment]
I had the same issue. I switched to using python3 and everything worked.

**Comment by ihabunek** [comment]
Yes, python 2 is not supported any longer. Not sure why pip lets you install with py2. I also need to add a notice on the installation instructions. Thanks for reporting.
