### ISSUE TITLE
'pip install toot' do not works for me  :-(

### ISSUE THREAD

**Issue by iztoogood** [ihabunek/toot#8]
` pip install toot
Downloading/unpacking toot
  Downloading toot-0.9.0-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in                                                                                                               run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundl                                                                                                              e=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_file                                                                                                              s
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2401, in requir                                                                                                              es
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2597, in _dep_m                                                                                                              ap
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2621, in _compu                                                                                                              te_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 49, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_                                                                                                              requirements
    "version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2686, in scan_l                                                                                                              ist
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'beautifulsoup4 ~=4.5.3', 'at', ' ~=4.5                                                                                                              .3')

Storing debug log for failure in /home/pi/.pip/pip.log`

**Comment by ihabunek** [comment]
Probably older version of pip which doesn't understand the `~=` directive.

Try running:
```
pip install --upgrade pip
```

**Comment by tleb** [comment]
I installed it using Python 3.5 a few hours ago (so we installed the same version) and it worked fine for me.

**Comment by iztoogood** [comment]
tanks a lot !!! \o/ --> it works
pip update:
```
sudo pip install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
then toto install :```

sudo pip install toot
Collecting toot
  Downloading toot-0.9.0-py2.py3-none-any.whl
Collecting future (from toot)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 73kB/s
Collecting beautifulsoup4~=4.5.3 (from toot)
  Downloading beautifulsoup4-4.5.3-py2-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 328kB/s
Collecting requests~=2.13 (from toot)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 87kB/s
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
Successfully built future
Installing collected packages: future, beautifulsoup4, requests, toot
  Found existing installation: requests 2.4.3
    Uninstalling requests-2.4.3:
      Successfully uninstalled requests-2.4.3
Successfully installed beautifulsoup4-4.5.3 future-0.16.0 requests-2.13.0 toot-0.9.0
```
```

**Comment by ihabunek** [comment]
Cool. I'll add a note to the readme, or edit the reqs so it works with older versions of pip.
