### ISSUE TITLE
Installing through pip results in an application that doesn't work

### ISSUE THREAD

**Issue by bas080** [ihabunek/toot#97]
Just ran `sudo pip install toot`. The installation resulted in some errors. 

```
Downloading/unpacking toot
  Downloading toot-0.21.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/toot/setup.py) egg_info for package toot
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    
Requirement already satisfied (use --upgrade to upgrade): requests>=2.13,<3.0 in /usr/local/lib/python2.7/dist-packages (from toot)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4>=4.5.0,<5.0 in /usr/local/lib/python2.7/dist-packages (from toot)
Requirement already satisfied (use --upgrade to upgrade): wcwidth>=0.1.7,<2.0 in /usr/local/lib/python2.7/dist-packages (from toot)
Installing collected packages: toot
  Running setup.py install for toot
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
      File "/usr/local/lib/python2.7/dist-packages/toot/output.py", line 56
        print(*args, **kwargs)
              ^
    SyntaxError: invalid syntax
    
      File "/usr/local/lib/python2.7/dist-packages/toot/wcstring.py", line 53
        yield from _wc_hard_wrap(line, length)
                 ^
    SyntaxError: invalid syntax
    
    SyntaxError: 'return' with argument inside generator (config_legacy.py, line 37)
    
    
    Installing toot script to /usr/local/bin
Successfully installed toot
Cleaning up...
```

Running too results in the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/toot", line 9, in <module>
    load_entry_point('toot==0.21.0', 'console_scripts', 'toot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/toot/console.py", line 5, in <module>
    import logging
  File "/usr/local/lib/python2.7/dist-packages/toot/logging.py", line 1, in <module>
    from logging import getLogger
ImportError: cannot import name getLogger
```

**Comment by dewomser** [comment]
pip uninstall toot
pip3 install toot
